name: Cargo Machete

#on: [push, pull_request]
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cargo-machete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Machete
        uses: bnjbvr/cargo-machete@main
