name: All; .png on git LFS

#on: [push, pull_request]
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-binary-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check that png files are on git LFS
      run: |
        binary_extensions="png"

        # Find binary files that are not tracked by Git LFS
        for ext in $binary_extensions; do
          if comm -23 <(git ls-files | sort) <(git lfs ls-files -n | sort) | grep "\.${ext}$"; then
            echo "Error: Found binary file with extension .$ext not tracked by git LFS. See CONTRIBUTING.md"
            exit 1
          fi
        done
